export interface Word {
    kanji: string;
    kana: string;
    romaji: string;
}

// LEVEL 1: 短い単語 (2-3文字) - 100語目標
export const WORDS_LEVEL_1: Word[] = [
    { kanji: '山', kana: 'やま', romaji: 'yama' }, { kanji: '海', kana: 'うみ', romaji: 'umi' },
    { kanji: '川', kana: 'かわ', romaji: 'kawa' }, { kanji: '空', kana: 'そら', romaji: 'sora' },
    { kanji: '星', kana: 'ほし', romaji: 'hosi' }, { kanji: '雲', kana: 'くも', romaji: 'kumo' },
    { kanji: '雨', kana: 'あめ', romaji: 'ame' }, { kanji: '雪', kana: 'ゆき', romaji: 'yuki' },
    { kanji: '風', kana: 'かぜ', romaji: 'kaze' }, { kanji: '音', kana: 'おと', romaji: 'oto' },
    { kanji: '猫', kana: 'ねこ', romaji: 'neko' }, { kanji: '犬', kana: 'いぬ', romaji: 'inu' },
    { kanji: '鳥', kana: 'とり', romaji: 'tori' }, { kanji: '虫', kana: 'むし', romaji: 'musi' },
    { kanji: '虹', kana: 'にじ', romaji: 'niji' }, { kanji: '森', kana: 'もり', romaji: 'mori' },
    { kanji: '石', kana: 'いし', romaji: 'isi' }, { kanji: '月', kana: 'つき', romaji: 'tuki' },
    { kanji: '旗', kana: 'はた', romaji: 'hata' }, { kanji: '火', kana: 'ひ', romaji: 'hi' },
    { kanji: '木', kana: 'き', romaji: 'ki' }, { kanji: '糸', kana: 'いと', romaji: 'ito' },
    { kanji: '針', kana: 'はり', romaji: 'hari' }, { kanji: '口', kana: 'くち', romaji: 'kuti' },
    { kanji: '手', kana: 'て', romaji: 'te' }, { kanji: '目', kana: 'め', romaji: 'me' },
    { kanji: '足', kana: 'あし', romaji: 'asi' }, { kanji: '顔', kana: 'かお', romaji: 'kao' },
    { kanji: '本', kana: 'ほん', romaji: 'hon' }, { kanji: '絵', kana: 'え', romaji: 'e' },
    { kanji: 'ペン', kana: 'ぺん', romaji: 'pen' }, { kanji: '傘', kana: 'かさ', romaji: 'kasa' },
    { kanji: '服', kana: 'ふく', romaji: 'huku' }, { kanji: '靴', kana: 'くつ', romaji: 'kutu' },
    { kanji: '耳', kana: 'みみ', romaji: 'mimi' }, { kanji: '鼻', kana: 'はな', romaji: 'hana' },
    { kanji: '門', kana: 'もん', romaji: 'mon' }, { kanji: '壁', kana: 'かべ', romaji: 'kabe' },
    { kanji: '床', kana: 'ゆか', romaji: 'yuka' }, { kanji: '池', kana: 'いけ', romaji: 'ike' },
    { kanji: '赤', kana: 'あか', romaji: 'aka' }, { kanji: '青', kana: 'あお', romaji: 'ao' },
    { kanji: '白', kana: 'しろ', romaji: 'siro' }, { kanji: '黒', kana: 'くろ', romaji: 'kuro' },
    { kanji: '柿', kana: 'かき', romaji: 'kaki' }, { kanji: '梨', kana: 'なし', romaji: 'nasi' },
    { kanji: '豆', kana: 'まめ', romaji: 'mame' }, { kanji: '芋', kana: 'いも', romaji: 'imo' },
    { kanji: '塩', kana: 'しお', romaji: 'sio' }, { kanji: '酢', kana: 'す', romaji: 'su' },
    { kanji: '酒', kana: 'さけ', romaji: 'sake' }, { kanji: '餅', kana: 'もち', romaji: 'moti' },
    { kanji: '笛', kana: 'ふえ', romaji: 'hue' }, { kanji: '枝', kana: 'えだ', romaji: 'eda' },
    { kanji: '根', kana: 'ね', romaji: 'ne' }, { kanji: '葉', kana: 'は', romaji: 'ha' },
    { kanji: '苔', kana: 'こけ', romaji: 'koke' }, { kanji: '岩', kana: 'いわ', romaji: 'iwa' },
    { kanji: '沼', kana: 'ぬま', romaji: 'numa' }, { kanji: '淵', kana: 'ふち', romaji: 'huti' },
    { kanji: '皿', kana: 'さら', romaji: 'sara' }, { kanji: '箸', kana: 'はし', romaji: 'hasi' },
    { kanji: '箱', kana: 'はこ', romaji: 'hako' }, { kanji: '鍵', kana: 'かぎ', romaji: 'kagi' },
    { kanji: '蓋', kana: 'ふた', romaji: 'huta' }, { kanji: '鐘', kana: 'かね', romaji: 'kane' },
    { kanji: '弓', kana: 'ゆみ', romaji: 'yumi' },
    { kanji: '矢', kana: 'や', romaji: 'ya' }, { kanji: '盾', kana: 'たて', romaji: 'tate' },
    { kanji: '鎌', kana: 'かま', romaji: 'kama' }, { kanji: '鋤', kana: 'すき', romaji: 'suki' },
    { kanji: '鍬', kana: 'くわ', romaji: 'kuwa' }, { kanji: '斧', kana: 'おの', romaji: 'ono' },
    { kanji: '紐', kana: 'ひも', romaji: 'himo' }, { kanji: '網', kana: 'あみ', romaji: 'ami' },
    { kanji: '歌', kana: 'うた', romaji: 'uta' }, { kanji: '詩', kana: 'し', romaji: 'si' },
    { kanji: '声', kana: 'こえ', romaji: 'koe' }, { kanji: '夢', kana: 'ゆめ', romaji: 'yume' },
    { kanji: '旅', kana: 'たび', romaji: 'tabi' }, { kanji: '馬', kana: 'うま', romaji: 'uma' },
    { kanji: '牛', kana: 'うし', romaji: 'usi' }, { kanji: '鹿', kana: 'しか', romaji: 'sika' },
    { kanji: '蟻', kana: 'あり', romaji: 'ari' }, { kanji: '蝉', kana: 'せみ', romaji: 'semi' },
    { kanji: '蜂', kana: 'はち', romaji: 'hati' }, { kanji: '蚊', kana: 'か', romaji: 'ka' },
    { kanji: '稲', kana: 'いね', romaji: 'ine' },
    { kanji: '麦', kana: 'むぎ', romaji: 'mugi' }, { kanji: '粟', kana: 'あわ', romaji: 'awa' },
    { kanji: '繭', kana: 'まゆ', romaji: 'mayu' }, { kanji: '殻', kana: 'から', romaji: 'kara' },
    { kanji: '棘', kana: 'とげ', romaji: 'toge' },
    { kanji: '罠', kana: 'わな', romaji: 'wana' }, { kanji: '嘘', kana: 'うそ', romaji: 'uso' },
    { kanji: '仇', kana: 'あだ', romaji: 'ada' }, { kanji: '恋', kana: 'こい', romaji: 'koi' },
    { kanji: '愛', kana: 'あい', romaji: 'ai' }, { kanji: '恩', kana: 'おん', romaji: 'on' },
    { kanji: '縁', kana: 'えん', romaji: 'en' }, { kanji: '運', kana: 'うん', romaji: 'un' },
    { kanji: '魂', kana: 'たま', romaji: 'tama' }, { kanji: '影', kana: 'かげ', romaji: 'kage' },
    { kanji: '霧', kana: 'きり', romaji: 'kiri' }, { kanji: '霜', kana: 'しも', romaji: 'simo' },
    { kanji: '露', kana: 'つゆ', romaji: 'tuyu' },
    { kanji: '磁石', kana: 'じしゃく', romaji: 'jisyaku' },
    { kanji: '象', kana: 'ぞう', romaji: 'zou' },
    { kanji: '図形', kana: 'ずけい', romaji: 'zukei' }
];

// LEVEL 2: 基本的な単語 (4-5文字) - 100語目標
export const WORDS_LEVEL_2: Word[] = [
    { kanji: 'リンゴ', kana: 'りんご', romaji: 'ringo' }, { kanji: 'ミカン', kana: 'みかん', romaji: 'mikan' },
    { kanji: 'イチゴ', kana: 'いちご', romaji: 'itigo' }, { kanji: 'メロン', kana: 'めろん', romaji: 'meron' },
    { kanji: 'スイカ', kana: 'すいか', romaji: 'suika' }, { kanji: 'レモン', kana: 'れもん', romaji: 'remon' },
    { kanji: 'バナナ', kana: 'ばなな', romaji: 'banana' }, { kanji: 'ブドウ', kana: 'ぶどう', romaji: 'budou' },
    { kanji: '学校', kana: 'がっこう', romaji: 'gakkou' }, { kanji: '先生', kana: 'せんせい', romaji: 'sensei' },
    { kanji: '友達', kana: 'ともだち', romaji: 'tomodati' }, { kanji: '勉強', kana: 'べんきょう', romaji: 'benkyou' },
    { kanji: '宿題', kana: 'しゅくだい', romaji: 'syukudai' }, { kanji: '漢字', kana: 'かんじ', romaji: 'kanji' },
    { kanji: '時計', kana: 'とけい', romaji: 'tokei' }, { kanji: '電話', kana: 'でんわ', romaji: 'denwa' },
    { kanji: '公園', kana: 'こうえん', romaji: 'kouen' }, { kanji: '病院', kana: 'びょういん', romaji: 'byouin' },
    { kanji: '図書', kana: 'としょ', romaji: 'tosyo' }, { kanji: '給食', kana: 'きゅうしょく', romaji: 'kyuusyoku' },
    { kanji: '元気', kana: 'げんき', romaji: 'genki' }, { kanji: '平和', kana: 'へいわ', romaji: 'heiwa' },
    { kanji: '勇気', kana: 'ゆうき', romaji: 'yuuki' }, { kanji: '希望', kana: 'きぼう', romaji: 'kibou' },
    { kanji: '不思議', kana: 'ふしぎ', romaji: 'fusigi' }, { kanji: '魔法', kana: 'まほう', romaji: 'mahou' },
    { kanji: '電車', kana: 'でんしゃ', romaji: 'densya' }, { kanji: '飛行機', kana: 'ひこうき', romaji: 'hikouki' },
    { kanji: '自動車', kana: 'じどうしゃ', romaji: 'jidousya' }, { kanji: '自転車', kana: 'じてんしゃ', romaji: 'jitensya' },
    { kanji: 'カメラ', kana: 'かめら', romaji: 'kamera' }, { kanji: 'ピアノ', kana: 'ぴあの', romaji: 'piano' },
    { kanji: 'ギター', kana: 'ぎたー', romaji: 'gita-' }, { kanji: 'ラジオ', kana: 'らじお', romaji: 'rajio' },
    { kanji: 'テレビ', kana: 'てれび', romaji: 'terebi' }, { kanji: 'ノート', kana: 'のーと', romaji: 'no-to' },
    { kanji: 'ボール', kana: 'ぼーる', romaji: 'bo-ru' }, { kanji: 'アイス', kana: 'あいす', romaji: 'aisu' },
    { kanji: 'ケーキ', kana: 'けーき', romaji: 'ke-ki' }, { kanji: 'パン屋', kana: 'ぱんや', romaji: 'panya' },
    { kanji: '花屋', kana: 'はなや', romaji: 'hanaya' }, { kanji: '床屋', kana: 'とこや', romaji: 'tokoya' },
    { kanji: 'お菓子', kana: 'おかし', romaji: 'okasi' }, { kanji: 'お弁当', kana: 'おべんとう', romaji: 'obentou' },
    { kanji: 'おにぎり', kana: 'おにぎり', romaji: 'onigiri' }, { kanji: 'うどん', kana: 'うどん', romaji: 'udon' },
    { kanji: 'そば', kana: 'そば', romaji: 'soba' }, { kanji: 'カレー', kana: 'かれー', romaji: 'kare-' },
    { kanji: '秘密', kana: 'ひみつ', romaji: 'himitu' }, { kanji: '散歩', kana: 'さんぽ', romaji: 'sanpo' },
    { kanji: '冒険', kana: 'ぼうけん', romaji: 'bouken' }, { kanji: '挑戦', kana: 'ちょうせん', romaji: 'tyousen' },
    { kanji: '成功', kana: 'せいこう', romaji: 'seikou' }, { kanji: '失敗', kana: 'しっぱい', romaji: 'sippai' }, { kanji: '笑顔', kana: 'えがお', romaji: 'egao' },
    { kanji: '涙', kana: 'なみだ', romaji: 'namida' }, { kanji: '感動', kana: 'かんどう', romaji: 'kandou' },
    { kanji: '景色', kana: 'けしき', romaji: 'kesiki' }, { kanji: '宇宙', kana: 'うちゅう', romaji: 'utyuu' },
    { kanji: '地球', kana: 'ちきゅう', romaji: 'tikyuu' }, { kanji: '世界', kana: 'せかい', romaji: 'sekai' },
    { kanji: '日本', kana: 'にほん', romaji: 'nihon' }, { kanji: '未来', kana: 'みらい', romaji: 'mirai' },
    { kanji: '過去', kana: 'かこ', romaji: 'kako' }, { kanji: '現在', kana: 'げんざい', romaji: 'genzai' },
    { kanji: '朝日', kana: 'あさひ', romaji: 'asahi' }, { kanji: '夕日', kana: 'ゆうひ', romaji: 'yuuhi' },
    { kanji: '夜空', kana: 'よぞら', romaji: 'yozora' }, { kanji: '銀河', kana: 'ぎんが', romaji: 'ginga' },
    { kanji: '彗星', kana: 'すいせい', romaji: 'suisei' }, { kanji: '星座', kana: 'せいざ', romaji: 'seiza' },
    { kanji: '惑星', kana: 'わくせい', romaji: 'wakusei' }, { kanji: '衛星', kana: 'えいせい', romaji: 'eisei' },
    { kanji: '空気', kana: 'くうき', romaji: 'kuuki' }, { kanji: '酸素', kana: 'さんそ', romaji: 'sanso' },
    { kanji: '水素', kana: 'すいそ', romaji: 'suiso' }, { kanji: '炭素', kana: 'たんそ', romaji: 'tanso' },
    { kanji: '窒素', kana: 'ちっそ', romaji: 'tisso' }, { kanji: '金属', kana: 'きんぞく', romaji: 'kinzoku' },
    { kanji: '宝石', kana: 'ほうせき', romaji: 'houseki' }, { kanji: '黄金', kana: 'おうごん', romaji: 'ougon' },
    { kanji: '白金', kana: 'はっきん', romaji: 'hakkin' }, { kanji: '真珠', kana: 'しんじゅ', romaji: 'sinju' },
    { kanji: '砂漠', kana: 'さばく', romaji: 'sabaku' }, { kanji: '森林', kana: 'しんりん', romaji: 'sinrin' },
    { kanji: '草原', kana: 'そうげん', romaji: 'sougen' }, { kanji: '火山', kana: 'かざん', romaji: 'kazan' },
    { kanji: '地震', kana: 'じしん', romaji: 'jisin' }, { kanji: '雷', kana: 'かみなり', romaji: 'kaminari' },
    { kanji: '嵐', kana: 'あらし', romaji: 'arasi' }, { kanji: '台風', kana: 'たいふう', romaji: 'taihuu' },
    { kanji: '吹雪', kana: 'ふぶき', romaji: 'hubuki' }, { kanji: '晴天', kana: 'せいてん', romaji: 'seiten' },
    { kanji: '曇天', kana: 'どんてん', romaji: 'donten' }, { kanji: '雨天', kana: 'うてん', romaji: 'uten' },
    { kanji: '雪天', kana: 'せってん', romaji: 'setten' }, { kanji: '朝顔', kana: 'あさがお', romaji: 'asagao' },
    { kanji: '向日葵', kana: 'ひまわり', romaji: 'himawari' }, { kanji: '紫陽花', kana: 'あじさい', romaji: 'ajisai' },
    { kanji: '春風', kana: 'はるかぜ', romaji: 'harukaze' }, { kanji: '夕立', kana: 'ゆうだち', romaji: 'yuudati' },
    { kanji: '初雪', kana: 'はつゆき', romaji: 'hatuyuki' }, { kanji: '木枯らし', kana: 'こがらし', romaji: 'kogarasi' },
    { kanji: '太陽', kana: 'たいよう', romaji: 'taiyou' }, { kanji: '月光', kana: 'げっこう', romaji: 'gekkou' },
    { kanji: '星空', kana: 'ほしぞら', romaji: 'hosizora' }, { kanji: '洞窟', kana: 'どうくつ', romaji: 'doukutu' },
    { kanji: '渓谷', kana: 'けいこく', romaji: 'keikoku' }, { kanji: '盆地', kana: 'ぼんち', romaji: 'bonti' },
    { kanji: '平野', kana: 'へいや', romaji: 'heiya' }
];

// LEVEL 3: 熟語・カタカナ (6-8文字) - 100語目標
export const WORDS_LEVEL_3: Word[] = [
    { kanji: 'プログラミング', kana: 'ぷろぐらみんぐ', romaji: 'puroguramingu' },
    { kanji: 'スマートフォン', kana: 'すまーとふぉん', romaji: 'sumatofon' },
    { kanji: 'インターネット', kana: 'いんたーねっと', romaji: 'inta-netto' },
    { kanji: '自動販売機', kana: 'じどうはんばいき', romaji: 'jidouhanbaiki' },
    { kanji: '救急車', kana: 'きゅうきゅうしゃ', romaji: 'kyuukyuusya' },
    { kanji: '消防自動車', kana: 'しょうぼうじどうしゃ', romaji: 'syouboujidousya' },
    { kanji: '宇宙飛行士', kana: 'うちゅうひこうし', romaji: 'utyuuhikousi' },
    { kanji: '天気予報', kana: 'てんきよほう', romaji: 'tenkiyohou' },
    { kanji: '電子レンジ', kana: 'でんしれんじ', romaji: 'densirenji' },
    { kanji: '空気清浄機', kana: 'くうきせいじょうき', romaji: 'kuukiseijouki' },
    { kanji: '植物園', kana: 'しょくぶつえん', romaji: 'syokubutuen' },
    { kanji: '図書館', kana: 'としょかん', romaji: 'tosyokan' },
    { kanji: '望遠鏡', kana: 'ぼうえんきょう', romaji: 'bouenkyou' },
    { kanji: '新幹線', kana: 'しんかんせん', romaji: 'sinkansen' },
    { kanji: '動物園', kana: 'どうぶつえん', romaji: 'doubutuen' },
    { kanji: '水族館', kana: 'すいぞくかん', romaji: 'suizokukan' },
    { kanji: '遊園地', kana: 'ゆうえんち', romaji: 'yuuenti' },
    { kanji: '体育館', kana: 'たいいくかん', romaji: 'taiikukan' },
    { kanji: '競技場', kana: 'きょうぎじょう', romaji: 'kyougijou' },
    { kanji: '人工衛星', kana: 'じんこうえいせい', romaji: 'jinkoueisei' },
    { kanji: '海底探査', kana: 'かいていたんさ', romaji: 'kaiteitansa' },
    { kanji: '深海魚の世界', kana: 'しんかいぎょのせかい', romaji: 'sinkaigyonosekai' },
    { kanji: '魔法の王国', kana: 'まほうのおうこく', romaji: 'mahounooukoku' },
    { kanji: '伝説の聖剣', kana: 'でんせつのせいけん', romaji: 'densetunoseiken' },
    { kanji: '暗黒の洞窟', kana: 'あんこくのどうくつ', romaji: 'ankokunodoukutu' },
    { kanji: '光の精霊', kana: 'ひかりのせいれい', romaji: 'hikarinoseirei' },
    { kanji: '炎の魔術師', kana: 'ほのおのまじゅつし', romaji: 'honoonomajutusi' },
    { kanji: '氷の女王', kana: 'こおりのじょおう', romaji: 'koorinojoou' },
    { kanji: '大地の鼓動', kana: 'だいちのこどう', romaji: 'daitinokodou' },
    { kanji: '風の歌声', kana: 'かぜのうたごえ', romaji: 'kazenoutagoe' },
    { kanji: '科学の進歩', kana: 'かがくのしんぽ', romaji: 'kagakunosinpo' },
    { kanji: '歴史の真実', kana: 'れきしのしんじつ', romaji: 'rekisinosinjitu' },
    { kanji: '芸術の感性', kana: 'げいじゅつのかんせい', romaji: 'geijutunokansei' },
    { kanji: '音楽の旋律', kana: 'おんがくのせんりつ', romaji: 'ongakunosenritu' },
    { kanji: '数学の論理', kana: 'すうがくのろんり', romaji: 'suugakunoronri' },
    { kanji: '言語の響き', kana: 'げんごのひびき', romaji: 'gengonohibiki' },
    { kanji: '笑顔の魔法', kana: 'えがおのまほう', romaji: 'egaonomahou' },
    { kanji: '涙の理由', kana: 'なみだのりゆう', romaji: 'namidanoriyuu' },
    { kanji: '勇者の旅立ち', kana: 'ゆうしゃのたびだち', romaji: 'yuusyanotabidati' },
    { kanji: '賢者の教え', kana: 'けんじゃのおしえ', romaji: 'kenjanoosie' },
    { kanji: '王様の休日', kana: 'おうさまのきゅうじつ', romaji: 'ousamanokyuujitu' },
    { kanji: '姫君の祈り', kana: 'ひめぎみのいのり', romaji: 'himegiminoinori' },
    { kanji: '騎士の誓い', kana: 'きしのちかい', romaji: 'kisinotikai' },
    { kanji: '冒険者の宿', kana: 'ぼうけんしゃのやど', romaji: 'boukensyanoyado' },
    { kanji: '商人の取引', kana: 'しょうにんのとりひき', romaji: 'syouninnotorihiki' },
    { kanji: '職人の技', kana: 'しょくにんのわざ', romaji: 'syokuninnowaza' },
    { kanji: '農民の収穫', kana: 'のうみんのしゅうかく', romaji: 'nouminnosyuukaku' },
    { kanji: '四季の変化', kana: 'しきのへんか', romaji: 'sikinohenka' },
    { kanji: '朝の始まり', kana: 'あさのはじまり', romaji: 'asanohajimari' },
    { kanji: '昼の賑わい', kana: 'ひるのにぎわい', romaji: 'hirunonigiwai' },
    { kanji: '夜の静寂', kana: 'よるのせいじゃく', romaji: 'yorunoseijaku' },
    { kanji: '明けの明星', kana: 'あけのみょうじょう', romaji: 'akenomyoujou' },
    { kanji: '宵の明星', kana: 'よいのみょうじょう', romaji: 'yoinomyoujou' },
    { kanji: '満月の夜', kana: 'まんげつのよる', romaji: 'mangetunoyoru' },
    { kanji: '新月の闇', kana: 'しんげつのやみ', romaji: 'singetunoyami' },
    { kanji: '星屑の海', kana: 'ほしくずのうみ', romaji: 'hosikuzunoumi' },
    { kanji: '太陽の恵み', kana: 'たいようのめぐみ', romaji: 'taiyounomegumi' },
    { kanji: '大地の恵み', kana: 'だいちのめぐみ', romaji: 'daitinomegumi' },
    { kanji: '海の恵み', kana: 'うみのめぐみ', romaji: 'uminomegumi' },
    { kanji: '森の恵み', kana: 'もりのめぐみ', romaji: 'morinomegumi' },
    { kanji: '命の輝き', kana: 'いのちのかがやき', romaji: 'inotinokagayaki' },
    { kanji: '愛の言葉', kana: 'あいのことば', romaji: 'ainokotoba' },
    { kanji: '友情の証', kana: 'ゆうじょうのあかし', romaji: 'yuujounoakasi' },
    { kanji: '真実の姿', kana: 'しんじつのすがた', romaji: 'sinjitunosugata' },
    { kanji: '希望の光', kana: 'きぼうのひかり', romaji: 'kibounohikari' },
    { kanji: '絶望の淵', kana: 'ぜつぼうのふち', romaji: 'zetubounohuti' },
    { kanji: '克服の道のり', kana: 'こくふくのみちのり', romaji: 'kokuhukunomitinori' },
    { kanji: '栄光の瞬間', kana: 'えいこうのしゅんかん', romaji: 'eikounosyunkan' },
    { kanji: '黄金の都', kana: 'おうごんのみやこ', romaji: 'ougonnomiyako' },
    { kanji: '空中庭園', kana: 'くうちゅうていえん', romaji: 'kuutyuuteien' },
    { kanji: '古代の遺跡', kana: 'こだいのいせき', romaji: 'kodainoiseki' },
    { kanji: '謎の暗号', kana: 'なぞのあんごう', romaji: 'nazonoangou' },
    { kanji: '秘密の合図', kana: 'ひみつのあいず', romaji: 'himitunoaizu' },
    { kanji: '奇跡の再会', kana: 'きせきのさいかい', romaji: 'kisekinosaikai' },
    { kanji: '運命の出会い', kana: 'うんめいのであい', romaji: 'unmeinodeai' },
    { kanji: '冒険の書', kana: 'ぼうけんのしょ', romaji: 'boukennosyo' },
    { kanji: '宝の地図', kana: 'たからのちず', romaji: 'takaranotizu' },
    { kanji: '伝説の龍', kana: 'でんせつのりゅう', romaji: 'densetunoryuu' },
    { kanji: '不老不死の薬', kana: 'ふろうふしのくすり', romaji: 'hurouhusinokusuri' },
    { kanji: '幻の果実', kana: 'まぼろしのかじつ', romaji: 'maborosinokajitu' },
    { kanji: '妖精の森', kana: 'ようせいのもり', romaji: 'youseinomori' },
    { kanji: '精霊の導き', kana: 'せいれいのみちびき', romaji: 'seireinomitibiki' },
    { kanji: '魔法の杖', kana: 'まほうのつえ', romaji: 'mahounotue' },
    { kanji: '聖なる盾', kana: 'せいなるたて', romaji: 'seinarutate' },
    { kanji: '暗黒の騎士', kana: 'あんこくのきし', romaji: 'ankokunokisi' },
    { kanji: '歴史のロマン', kana: 'れきしのろまん', romaji: 'rekisinoroman' },
    { kanji: '未来の予感', kana: 'みらいのよかん', romaji: 'mirainoyokan' },
    { kanji: '芸術の極み', kana: 'げいじゅつのきわみ', romaji: 'geijutunokiwami' },
    { kanji: '科学の光', kana: 'かがくのひかり', romaji: 'kagakunohikari' },
    { kanji: '魂の輝き', kana: 'たましいのかがやき', romaji: 'tamasiinokagayaki' },
    { kanji: '心の平和', kana: 'こころのへいわ', romaji: 'kokoronoheiwa' },
    { kanji: '自由の翼', kana: 'じゆうのつばさ', romaji: 'jiyuunotubasa' },
    { kanji: '栄光の架橋', kana: 'えいこうのかけはし', romaji: 'eikounokakehasi' },
    { kanji: '勇気の印', kana: 'ゆうきのしるし', romaji: 'yuukinosirusi' },
    { kanji: '希望の鐘', kana: 'きぼうのかね', romaji: 'kibounokane' },
    { kanji: '真実の愛', kana: 'しんじつのあい', romaji: 'sinjitunoai' },
    { kanji: '無限の宇宙', kana: 'むげんのうちゅう', romaji: 'mugennoutyuu' }
];

// LEVEL 4: 長い単語・複合語 (9文字以上) - 60語目標
export const WORDS_LEVEL_4: Word[] = [
    { kanji: '新幹線旅行', kana: 'しんかんせんりょこう', romaji: 'sinkansenryokou' },
    { kanji: '救急車出動', kana: 'きゅうきゅうしゃしゅつどう', romaji: 'kyuukyuusyasyutudou' },
    { kanji: '顕微鏡観察', kana: 'けんびきょうかんさつ', romaji: 'kenbikyoukansatu' },
    { kanji: '人工知能開発', kana: 'じんこうちのうかいはつ', romaji: 'jinkoutinoukaihatu' },
    { kanji: '仮想現実体験', kana: 'かそうげんじつたいけん', romaji: 'kasougenjitutaiken' },
    { kanji: '地球温暖化対策', kana: 'ちきゅうおんだんかたいさく', romaji: 'tikyuuondankataisaku' },
    { kanji: '環境保護活動', kana: 'かんきょうほごかつどう', romaji: 'kankyouhogokatudou' },
    { kanji: '風力発電所', kana: 'ふうりょくはつでんしょ', romaji: 'huuryokuhatudensyo' },
    { kanji: '宇宙遊泳体験', kana: 'うちゅうゆうえいたいけん', romaji: 'utyuuyuueitaiken' },
    { kanji: '生物多様性', kana: 'せいぶつたようせい', romaji: 'seibututayousei' },
    { kanji: '太陽光発電', kana: 'たいようこうはつでん', romaji: 'taiyoukouhatuden' },
    { kanji: '情報処理能力', kana: 'じょうほうしょりのうりょく', romaji: 'jouhousyorinouryoku' },
    { kanji: '高度情報化社会', kana: 'こうどじょうほうかしゃかい', romaji: 'koudojouhoukasyakai' },
    { kanji: '少子高齢化問題', kana: 'しょうしこうれいかもんだい', romaji: 'syousikoureikamondai' },
    { kanji: '持続可能開発目標', kana: 'じぞくかのうかいはつもくひょう', romaji: 'jizokukanoukaihatumokuhyou' },
    { kanji: '地殻変動の影響', kana: 'ちかくへんどうのえいきょう', romaji: 'tikakuhendounoeikyou' },
    { kanji: '深海探査艇の冒険', kana: 'しんかいたんさていのぼうけん', romaji: 'sinkaitansateinobouken' },
    { kanji: '宇宙ステーション生活', kana: 'うちゅうすてーしょんせいかつ', romaji: 'utyuusuteesyonseikatu' },
    { kanji: '遺伝子組み換え食品', kana: 'いでんしくみかえしょくひん', romaji: 'idensikumikaesyokuhin' },
    { kanji: '量子コンピューター', kana: 'りょうしこんぴゅーたー', romaji: 'ryousikonpyu-ta-' },
    { kanji: '再生可能エネルギー', kana: 'さいせいかのうえねるぎー', romaji: 'saiseikanouenerugi-' },
    { kanji: '核融合発電の夢', kana: 'かくゆうごうはつでんのゆめ', romaji: 'kakuyuugouhatudennoyume' },
    { kanji: '温室効果ガスの削減', kana: 'おんしつこうかがすのさくげん', romaji: 'onsitukoukagasunosakugen' },
    { kanji: '絶滅危惧種の保護', kana: 'ぜつめつきぐしゅのほご', romaji: 'zetumetukigusyunohogo' },
    { kanji: '森林破壊の防止', kana: 'しんりん破壊の防止', romaji: 'sinrinhakainobousi' },
    { kanji: '海洋汚染の解決', kana: 'かいようおせんのかいけつ', romaji: 'kaiyouosennokaiketu' },
    { kanji: '世界遺産の登録', kana: 'せかいいさんのとうろく', romaji: 'sekaiisannotouroku' },
    { kanji: '無形文化遺産の継承', kana: 'むけいぶんかいさんのけいしょう', romaji: 'mukeibunkaisannokeisyou' },
    { kanji: '国際平和の維持', kana: 'こくさいへいわのいじ', romaji: 'kokusaiheiwanoniji' },
    { kanji: '人道支援の活動', kana: 'じんどうしえんのかかつどう', romaji: 'jindousiennokatudou' },
    { kanji: '経済発展の歴史', kana: 'けいざいはってんのれきし', romaji: 'keizaihattennorekisi' },
    { kanji: '民主主義の発展', kana: 'みんしゅしゅぎのはってん', romaji: 'minsyusyuginohatten' },
    { kanji: '交通安全のルール', kana: 'こうつうあんぜんのるーる', romaji: 'koutuuanzennoru-ru' },
    { kanji: '公共交通機関の利用', kana: 'こうきょうこうつうきかんのりよう', romaji: 'koukyoukoutuukikannoriyou' },
    { kanji: '不審者対策の指導', kana: 'ふしんしゃたいさくのしどう', romaji: 'husinsyataisakunosidou' },
    { kanji: '震災対策の訓練', kana: 'しんさいたいさくのくんれん', romaji: 'sinsaitaisakunokunren' },
    { kanji: '火災報知機の点検', kana: 'かさいほうちきのてんけん', romaji: 'kasaihoutikinotenken' },
    { kanji: '不撓不屈の努力', kana: 'ふとうふくつのどりょく', romaji: 'hutouhukutunodoryoku' },
    { kanji: '大願成就の祈り', kana: 'たいがんじょうじゅのいのり', romaji: 'daiganjoujunoinori' },
    { kanji: '暗中模索の探究', kana: 'あんちゅうもさくのたんきゅう', romaji: 'antyuumosakunotankyuu' },
    { kanji: '試行錯誤の連続', kana: 'しこうさくごのれんぞく', romaji: 'sikousakugonorenzoku' },
    { kanji: '臨機応変な対応', kana: 'りんきおうへんなたいおう', romaji: 'rinkiouhennataiou' },
    { kanji: '温故知新の精神', kana: 'おんこちしんのせいしん', romaji: 'onkotisinnoseisin' },
    { kanji: '一致団結の力', kana: 'いっちだんけつのちから', romaji: 'ittidanketunotikara' },
    { kanji: '切磋琢磨の日々', kana: 'せっさたくまのひび', romaji: 'sessatakumanohibi' },
    { kanji: '率先垂範の行動', kana: 'そっせんすいはんのこうどう', romaji: 'sossensuihannokoudou' }
];

// LEVEL 5: 短いフレーズ・文章 - 60語目標
export const WORDS_LEVEL_5: Word[] = [
    { kanji: '無限の可能性を信じて', kana: 'むげんのかのうせいをしんじて', romaji: 'mugennokanouseiosinjite' },
    { kanji: '不思議な大冒険の始まり', kana: 'ふしぎなだいぼうけんのはじまり', romaji: 'fusiginadaiboukennohajimari' },
    { kanji: '伝説の聖剣を求めて', kana: 'でんせつのせいけんをもとめて', romaji: 'densetunoseikenwomotomete' },
    { kanji: '友情の絆は永遠に', kana: 'ゆうじょうのきずなはえいえんに', romaji: 'yuujounokizunahaeienni' },
    { kanji: '光り輝く未来への一歩', kana: 'ひかりかがやくみらいへのいっぽ', romaji: 'hikarikagayakumiraihenoippo' },
    { kanji: '平和な世界を築くために', kana: 'へいわなせかいをきずくために', romaji: 'heiwanasekaiwokizukutameni' },
    { kanji: '一歩ずつ確実に前へ進む', kana: 'いっぽずつかくじつまえへすすむ', romaji: 'ippojutukakuzitumaehesusumu' },
    { kanji: '虹の橋を渡る勇気を持って', kana: 'にじのはしをわたるゆうきをもって', romaji: 'nijinohasiwowataruyuukiwomotte' },
    { kanji: '心の扉を開いて未来を見よう', kana: 'こころのとびらをひらいてみらいをみよう', romaji: 'kokoronotobirawohiraitemiraiwomiyou' },
    { kanji: 'あきらめない心が奇跡を起こす', kana: 'あきらめないこころがきせきをおこす', romaji: 'akiramenaikokorogakisekiwookosu' },
    { kanji: '輝く星の海に夢を浮かべて', kana: 'かがやくほしのうみにゆめをうかべて', romaji: 'kagayakuhosinoumiyumewoukabete' },
    { kanji: '失敗は成功の母である', kana: 'しっぱいはせいこうのははである', romaji: 'sippaihaseikounohahadearu' },
    { kanji: '塵も積もれば山となる', kana: 'ちりもつもればやまとなる', romaji: 'tirimotumorebayamatunaru' },
    { kanji: '継続は力なり', kana: 'けいぞくはちからなり', romaji: 'keizokuhatikaranari' },
    { kanji: '思い立ったが吉日', kana: 'おもいたったがきじつ', romaji: 'omoitattagakijitu' },
    { kanji: '急がば回れ', kana: 'いそがばまわれ', romaji: 'isogabamaware' },
    { kanji: '笑う門には福来る', kana: 'わらうかどにはふくきたる', romaji: 'waraukadoniwahukukitaru' },
    { kanji: '情けは人のためならず', kana: 'なさけはひとのためならず', romaji: 'nasakehahitonotamenarazu' },
    { kanji: '案ずるより産むが易し', kana: 'あんずるよりうむがやすし', romaji: 'anjuruyoriumugayasusi' },
    { kanji: '石の上にも三年', kana: 'いしのうえにもさんねん', romaji: 'isinouenimosannen' },
    { kanji: '雨降って地固まる', kana: 'あめふってじかたまる', romaji: 'amehuttejikatamaru' },
    { kanji: '千里の道も一歩から', kana: 'せんりのみちもいっぽから', romaji: 'senrinomitumoippokara' },
    { kanji: '百聞は一見に如かず', kana: 'ひゃくぶんはいっけんにしかず', romaji: 'hyakubunhaikkennisikazu' },
    { kanji: '初心忘るべからず', kana: 'しょしんわするべからず', romaji: 'syosinwasurubekarazu' },
    { kanji: '虎穴に入らずんば虎子を得ず', kana: 'こけつにいらずんば虎子を得ず', romaji: 'koketuniirazunbakozioezu' },
    { kanji: '自業自得', kana: 'じごうじとく', romaji: 'jigouzitoku' },
    { kanji: '因果応報', kana: 'いんがおうほう', romaji: 'ingaouhou' },
    { kanji: '一期一会', kana: 'いちごいちえ', romaji: 'itigoitie' },
    { kanji: '一石二鳥', kana: 'いっせきにちょう', romaji: 'issekinitiyou' },
    { kanji: '一善をなす', kana: 'いちぜんをなす', romaji: 'itizenwonasu' },
    { kanji: '勇猛果敢に挑む', kana: 'ゆうもうかかんといどむ', romaji: 'yuumoukakanniidomu' },
    { kanji: '不撓不屈の精神', kana: 'ふとうふくつのせいしん', romaji: 'hutouhukutunoseisin' },
    { kanji: '和気藹々', kana: 'わきあいあい', romaji: 'wakiaiai' },
    { kanji: '森羅万象の不思議', kana: 'しんらばんしょうのふしぎ', romaji: 'sinrabansyounohusigi' },
    { kanji: '喜怒哀楽を共にする', kana: 'きどあいらくをともにする', romaji: 'kidoairakuwotomonisuru' },
    { kanji: '千変万化の世界', kana: 'せんぺんばんかのせかい', romaji: 'senpenbankanosekai' },
    { kanji: '自由奔放に生きる', kana: 'じゆうほんぽうにいきる', romaji: 'jiyuuhonpouniikiru' },
    { kanji: '温故知新の教え', kana: 'おんこちしんのおしえ', romaji: 'onkotisinnnoosie' },
    { kanji: '一心不乱に打ち込む', kana: 'いっしんふらんにうちこむ', romaji: 'issinhuranniutikomu' },
    { kanji: '明日は明日の風が吹く', kana: 'あしたはあしたのかぜがふく', romaji: 'asitawaasitanokazegahuku' },
    { kanji: '嘘も方便の教え', kana: 'うそもほうべんのおしえ', romaji: 'usomohoubennoosie' },
    { kanji: '果報は寝て待て', kana: 'かほうはねてまて', romaji: 'kahouhanetemate' },
    { kanji: '弘法筆を選ばず', kana: 'こうぼうふでをえらばず', romaji: 'koubouhudewoerabazu' },
    { kanji: '猿も木から落ちる', kana: 'さるもきからおちる', romaji: 'sarumokikaraotiru' },
    { kanji: '勝って兜の緒を締めよ', kana: 'かってかぶとのおをしめよ', romaji: 'kattekabutunooosimeyo' },
    { kanji: '善は急げと言います', kana: 'ぜんはいそげといいます', romaji: 'zenhaisogetoiimasu' },
    { kanji: '棚からぼたもち', kana: 'たなからぼたもち', romaji: 'tanakarabotamoti' }
];
